#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libite
Version  : 2.1.0
Release  : 3
URL      : https://github.com/troglobit/libite/releases/download/v2.1.0/libite-2.1.0.tar.xz
Source0  : https://github.com/troglobit/libite/releases/download/v2.1.0/libite-2.1.0.tar.xz
Summary  : Frog DNA, basically
Group    : Development/Tools
License  : MIT
Requires: libite-lib = %{version}-%{release}
Requires: libite-license = %{version}-%{release}

%description
-lite | Frog DNA, basically
===========================
[![Travis Status][]][Travis]

%package dev
Summary: dev components for the libite package.
Group: Development
Requires: libite-lib = %{version}-%{release}
Provides: libite-devel = %{version}-%{release}
Requires: libite = %{version}-%{release}

%description dev
dev components for the libite package.


%package doc
Summary: doc components for the libite package.
Group: Documentation

%description doc
doc components for the libite package.


%package lib
Summary: lib components for the libite package.
Group: Libraries
Requires: libite-license = %{version}-%{release}

%description lib
lib components for the libite package.


%package license
Summary: license components for the libite package.
Group: Default

%description license
license components for the libite package.


%prep
%setup -q -n libite-2.1.0
cd %{_builddir}/libite-2.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579718878
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1579718878
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libite
cp %{_builddir}/libite-2.1.0/LICENSE %{buildroot}/usr/share/package-licenses/libite/f1e6c597a77ddf6d594fa67d3039ab4fc32d289a
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/lite/conio.h
/usr/include/lite/lite.h
/usr/include/lite/queue.h
/usr/include/lite/strdupa.h
/usr/include/lite/strlite.h
/usr/include/lite/strndupa.h
/usr/include/lite/strnlen.h
/usr/include/lite/tree.h
/usr/lib64/libite.so
/usr/lib64/pkgconfig/libite.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libite/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libite.so.5
/usr/lib64/libite.so.5.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libite/f1e6c597a77ddf6d594fa67d3039ab4fc32d289a
