#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libite
Version  : 2.0.2
Release  : 2
URL      : https://github.com/troglobit/libite/releases/download/v2.0.2/libite-2.0.2.tar.xz
Source0  : https://github.com/troglobit/libite/releases/download/v2.0.2/libite-2.0.2.tar.xz
Summary  : Frog DNA, basically
Group    : Development/Tools
License  : MIT
Requires: libite-lib
Requires: libite-license

%description
-lite | Frog DNA, basically
===========================
[![Travis Status][]][Travis]

%package dev
Summary: dev components for the libite package.
Group: Development
Requires: libite-lib = %{version}-%{release}
Provides: libite-devel = %{version}-%{release}

%description dev
dev components for the libite package.


%package doc
Summary: doc components for the libite package.
Group: Documentation

%description doc
doc components for the libite package.


%package lib
Summary: lib components for the libite package.
Group: Libraries
Requires: libite-license = %{version}-%{release}

%description lib
lib components for the libite package.


%package license
Summary: license components for the libite package.
Group: Default

%description license
license components for the libite package.


%prep
%setup -q -n libite-2.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537475669
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1537475669
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libite
cp LICENSE %{buildroot}/usr/share/doc/libite/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/lite/conio.h
/usr/include/lite/lite.h
/usr/include/lite/queue.h
/usr/include/lite/strdupa.h
/usr/include/lite/strlite.h
/usr/include/lite/strndupa.h
/usr/include/lite/strnlen.h
/usr/include/lite/tree.h
/usr/lib64/libite.so
/usr/lib64/pkgconfig/libite.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libite/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libite.so.5
/usr/lib64/libite.so.5.0.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/libite/LICENSE
